normal:
  i: switch_to_insert_mode

  h: move_back  
  j: move_down
  k: move_up
  l: move_forward

  A: switch_to_insert_line_end
  I: switch_to_insert_line_start
  o: switch_to_insert_new_line_next
  O: switch_to_insert_new_line_prev

  d: delete_char

  g_g: go_to_start_line
  g_e: go_to_end_line

insert:
  esc: switch_to_normal_mode
  left: move_back
  right: move_forward
  up: move_up
  down: move_down
  backspace: delete_char
  enter: new_line