[package]
name = "duzzy-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.3"
ropey = "1.6.0"
anyhow = "1.0.70"

crossterm = "0.26.1"
tui = { version = "0.19.0", default-features = false, features = ["crossterm"] }

strum = { version = "0.24.1", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }

[lib]
name = "duzzy"
path = "src/lib.rs"
